image: node

stages:
 # I just want to lint, so I will create a "lint" stage
 - lint

# Lets name our Job eslint, because that's what it's doing.
eslint:
 stage: lint
 script:
    # install eslint
    - npm --proxy http://jurosutantra:41455108@cache.itb.ac.id:8080 install
    - node_modules\.bin\eslint src/*.js --fix
    - node_modules\.bin\eslint src/*.jsx --fix